name: Create Docker Images
on:
  push:
    branches:
      - test_actions
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          always-auth: true
      - name: Configure npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "@micahg:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" >> .npmrc
      - name: Get Version
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "container_version=$VERSION" >> "$GITHUB_ENV"
      - name: Download UI Package
        run: |
          npm config set registry="https://npm.pkg.github.com/"
          UI_PKG=$(npm pack @micahg/ntt)
          echo "ui_package=$UI_PKG" >> "$GITHUB_ENV"
      - name: Download API Package
        run: |
          API_PKG=$(npm pack @micahg/nttsrv)
          echo "api_package=$API_PKG" >> "$GITHUB_ENV"
      - name: Build Docker Images
        run: |
          mkdir ntt
          mkdir nttsrv
          echo $UI_PKG
          echo $API_PKG
          tar xvf $ui_package -C ntt
          tar xvf $api_package -C nttsrv